### ISSUE TITLE
Skype開催について

### ISSUE THREAD

**Issue by ToshihitoKon** [Linux-FUN/DotAsterisk_online#13]
Skypeで話しながら作業したいという声もあるのでちょいと考えてます。

条件は
- 強制参加にしないこと（静かに作業したい人もいるので）
- 誰でも自由に入れること
- 参加方法が公開されていること

辺りだと思います。

誰かSkype側をまとめる人を立てて、その人に連絡すれば入れるよ、みたいなことを書いたファイルをこのリポジトリに乗っけておけばいいかなって思ってます。

条件と方針について意見等あればどうぞ

**Comment by lrf141** [comment]
いいんでねぇか??
雑談しながら的なやつありだとおもう

**Comment by ToshihitoKon** [comment]
第11回に試験的にSkype枠を設置しました。
誰かいい感じに会議の窓口になってくれる人を募集します。
見つからなければ僕が仮にやります

**Comment by chikuwait** [comment]
じゃあ自分が窓口になりましょうかね

**Comment by uehara1414** [comment]
なら、chikuwait さんに事前に Gitter のPrivateChat で自分のSkypeIDを伝えて、それを元にグループを作ってもらうってのがいいかな

**Comment by ToshihitoKon** [comment]
大体安定した感じなので閉じます
