### ISSUE TITLE
HPほしいね

### ISSUE THREAD

**Issue by ToshihitoKon** [Linux-FUN/DotAsterisk_online#14]
pagesでもいいから何かほしいね
Linux-FUNのページ作るのが先かな。

**Comment by ToshihitoKon** [comment]
## 書いて欲しいもの
- readmeの内容
  - 参加方法
  - 流れ
  - Discord参加方法
  - 内容
  - GitterのURL

## 余裕があれば作ってみて欲しいもの
- 次回のconnpassページヘのリンク
  - 自動取得できると最高

**Comment by rf0321** [comment]
やってみます

**Comment by ToshihitoKon** [comment]
作ってくれました
https://linux-fun.github.io/dotasterisk/

以後修正は別issue立てる感じで
github.ioのリポジトリじゃなくてこっちのリポジトリでissue管理しましょう
