### ISSUE TITLE
#23 17/3/31

### ISSUE THREAD

**Issue by lrf141** [Linux-FUN/DotAsterisk_online#30]

**Comment by lrf141** [comment]
# この素晴らしいタスクに祝福を！

- javaでデザパタ頑張る
- 暇があったら深層学習の再帰型ニューラルネットのお勉強

**Comment by AkashiAkatsuki** [comment]
## うらら迷作業
 - Unity弾丸発射チャレンジ

**Comment by katainaka0503** [comment]
# やること
- [Category Theory for Programmers](https://bartoszmilewski.com/2014/10/28/category-theory-for-programmers-the-preface/)読む

**Comment by chikuwait** [comment]
# やること
- RubyでLISPインタプリタを作る

**Comment by ts-uc** [comment]
# やること

* 人間失格を読破する
* 時間が終わったら高速バスの料金を納めてくる

**Comment by ToshihitoKon** [comment]
## やること

- yaourt -S skype
- カーネルモジュール検証環境建てる

**Comment by ts-uc** [comment]
# やったこと
* 人間失格の, 第3の手記の1まで読み終わった

**Comment by lrf141** [comment]
# 完了されたこの素晴らしいタスク達

- デザパタ
- ファクトリパターン
- シングルトンパターン
- フライウェイトパターン

深層学習の勉強は進んでないので続けます。

**Comment by AkashiAkatsuki** [comment]
## 奇々も怪々お尋ねします　進捗進捗おいでませ
 - 弾丸のプレハブを作った
 - ExcuteEvents.Excute動け（エクスキューションのポーズ）

**Comment by chikuwait** [comment]
# おんぎゃあばぶばぶ

- 字句解析まで作った

**Comment by rf0321** [comment]
#この素晴らしい世界に祝福を！
・バイトのタスク無理やりプッシュした

**Comment by katainaka0503** [comment]
# やったこと
- 少し読んだ。

**Comment by ToshihitoKon** [comment]
## やったこと
- yaourtのskype、lib32めっちゃ入れるしgpg鍵なかったしなので断念
- 飯食った
